config/routes.rb
Rails.application.routes.draw do
  root to: "job_postings#index"

  resources :job_postings, only: [:create, :edit, :index, :new, :show, :update]
  resources :locations, only: [:create, :new, :show]

  namespace :api do
    namespace :v1 do
      resources :categories, only: [:index]
      resources :job_posters, only: [:index]
      resources :job_posting_statuses, only: [:index]
      resources :job_postings, only: [:create, :index]
      resources :locations, only: [:index]
      resources :regions, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :job_postings, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/job_poster.rb
class JobPoster < ApplicationRecord
  has_many :job_postings, dependent: :destroy

  def full_name
    [first_name, last_name].compact.join(" ")
  end
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  belongs_to :job_poster
  belongs_to :category
  belongs_to :location

  enum status: {
    new_post: 0,
    pending: 1,
    complete: 2
  }

  validates :title, presence: true
  validates :description, presence: true

  after_initialize :set_defaults

  self.per_page = 10

  private

  def set_defaults
    self.posted_at ||= Time.zone.now
    self.status ||= statuses[:new_post]
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :job_postings, dependent: :destroy
  belongs_to :region

  validates :name, presence: true
  validates :street_address_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  scope :grouped_by_region, -> do
    group(:region_id)
  end
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :locations, dependent: :destroy

  validates :name, presence: true
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < ApiController
      def index
        render json: Category.all
      end
    end
  end
end

app/controllers/api/v1/job_posters_controller.rb
module Api
  module V1
    class JobPostersController < ApiController
      def index
        render json: JobPoster.all
      end
    end
  end
end

app/controllers/api/v1/job_posting_statuses_controller.rb
module Api
  module V1
    class JobPostingStatusesController < ApiController
      def index
        statuses = JobPosting.statuses.keys.map do |status|
          { name: status.titleize, value: status }
        end

        render json: statuses
      end
    end
  end
end

app/controllers/api/v1/job_postings_controller.rb
module Api
  module V1
    class JobPostingsController < ApiController
      def create
        @job_posting = JobPosting.new(job_posting_params)

        if @job_posting.save
          render json: @job_posting, status: :created
        else
          render json: @job_posting.errors, status: :unprocessable_entity
        end
      end

      def index
        @job_postings = JobPosting.all
          .includes(:job_poster, :category, :location)

        render json: @job_postings
      end

      private

      def job_posting_params
        params.require(:job_posting)
          .permit(:title, :job_poster_id, :category_id, :location_id, :status, :description)
      end
    end
  end
end

app/controllers/api/v1/locations_controller.rb
module Api
  module V1
    class LocationsController < ApiController
      def index
        render json: Location.all
      end
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:edit, :show]

  def create
    @job_posting = JobPosting.new(job_posting_params)

    if @job_posting.save
      redirect_to @job_posting
    else
      render :new
    end
  end

  def edit; end

  def index
    @job_postings = JobPosting.includes(:job_poster, :category, :location)
      .paginate(:page => params[:page])
      .decorate
  end

  def new
    @job_posting = JobPosting.new
  end

  def show; end

  def update
    @job_posting = JobPosting.find(params[:id])

    if @job_posting.update(job_posting_params)
      redirect_to @job_posting
    else
      render :edit
    end
  end

  private

  def job_posting_params
    params.require(:job_posting)
      .permit(:title, :job_poster_id, :category_id, :location_id, :status, :description)
  end

  def set_job_posting
    @job_posting = JobPosting.find(params[:id]).decorate
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show]

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location
    else
      render :new
    end
  end

  def new
    @location = Location.new
  end

  def show; end

  private

  def location_params
    params.require(:location)
      .permit(:name, :street_address_1, :street_address_2, :city, :state, :zip_code, :region_id)
  end

  def set_location
    @location = Location.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_format_helper.rb
module TimeFormatHelper
  def ldate_time(time, hash = {})
    time ? l(time, hash) : nil
  end
end

app/views/job_postings/_form.html.erb
<% if @job_posting.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @job_posting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @job_posting, local: true do |form| %>
  <div class="field_with_errors">
    <%= form.label(:title, for: :job_posting_title) %>
    <%= form.text_field(:title, id: :job_posting_title, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:job_poster_id, for: :job_posting_job_poster) %>
    <%= form.select(:job_poster_id, JobPoster.all.map { |poster| [poster.full_name.titleize, poster.id] }, { prompt: t(".poster_prompt") }, { id: :job_posting_job_poster, class: "form-control" }) %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:category_id, for: :job_posting_category) %>
    <%= form.select(:category_id, Category.all.map { |category| [category.name.titleize, category.id] }, { prompt: t(".category_prompt") }, { id: :job_posting_category, class: "form-control" }) %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:location_id, for: :job_posting_location) %>
    <%= form.select(:location_id, Location.all.map { |location| [location.name, location.id] }, { prompt: t(".location_prompt") }, { id: :job_posting_location, class: "form-control" }) %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:status, for: :job_posting_status) %>
    <%= form.select(:status, JobPosting.statuses.keys.map { |status| [status.titleize, status] }, { }, { id: :job_posting_status, class: "form-control" }) %>
  </div>

  <div class="field_with_errors">
    <%= form.label :description, for: :job_posting_description %>
    <%= form.text_area(:description, { rows: "3", id: :job_posting_description, class: "form-control" }) %>
  </div>

  <%= form.submit action_name, class: "btn btn-default action-btn" %>
<% end %>

app/views/job_postings/_posting_heading.html.erb
<div class="heading">
  <h1><%= t(".title") %></h1>
  <p><%= link_to t(".action.back"), job_postings_path %></p>
</div>

app/views/job_postings/edit.html.erb
<%= render "posting_heading" %>

<%= render "form", action_name: t("job_postings.form.update") %>

app/views/job_postings/index.html.erb
<div class="heading">
  <h1><%= t(".title") %></h1>
</div>

<table id="job-postings" class="tablesorter tablesorter-blue table">
  <thead>
    <tr>
      <th><span class="posting-date"><%= t(".date") %></span></th>
      <th><span class="posting-title"><%= t(".job_title") %></span></th>
      <th><span class="posting-poster"><%= t(".poster") %></span></th>
      <th><span class="posting-category"><%= t(".category") %></span></th>
      <th><span class="posting-location"><%= t(".location") %></span></th>
      <th><span class="posting-status"><%= t(".status") %></span></th>
      <th><span class="posting-actions"><%= t(".actions") %></span></th>
  </thead>
  <tbody>
    <% @job_postings.each do |posting| %>
      <tr class="job-posting-<%= posting.id %>">
        <td class="posting-date"><%= ldate_time(posting.posted_at, format: :short) %></td>
        <td class="posting-title"><%= posting.title %></td>
        <td class="posting-poster"><%= posting.poster_name %></td>
        <td class="posting-category"><%= posting.category_name %></td>
        <td class="posting-location"><%= posting.location_city %></td>
        <td class="posting-status"><%= posting.status %></td>
        <td class="posting-actions">
          <%= link_to t(".action.view"), posting %>
          <%= link_to t(".action.edit"), edit_job_posting_path(posting) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @job_postings %>

<div class="actions">
  <%= link_to t(".action.new_job"), new_job_posting_path, class: "btn btn-primary" %>
  <%= link_to t(".action.new_location"), new_location_path, class: "btn btn-default" %>
</div>

app/views/job_postings/new.html.erb
<%= render "posting_heading" %>

<%= render "form", action_name: t("job_postings.form.create") %>

app/views/job_postings/show.html.erb
<%= render "posting_heading" %>

<div class="job-posting">
  <dl class="dl-horizontal">
    <dt><%= t(".date") %></dt>
    <dd class="posting-date"><%= ldate_time(@job_posting.posted_at, format: :short) %></dd>
    <dt><%= t(".title") %></dt>
    <dd class="posting-title"><%= @job_posting.title %></dd>
    <dt><%= t(".poster") %></dt>
    <dd class="posting-poster"><%= @job_posting.poster_name %></dd>
    <dt><%= t(".category") %></dt>
    <dd class="posting-category"><%= @job_posting.category_name %></dd>
    <dt><%= t(".location") %></dt>
    <dd class="posting-location"><%= simple_format(@job_posting.location_full_address) %></dd>
    <dt><%= t(".status") %></dt>
    <dd class="posting-status"><%= @job_posting.status %></dd>
    <dt><%= t(".description") %></dt>
    <dd class="posting-description"><%= @job_posting.description %></dd>
  </dl>
</div>

<div class="actions">
  <%= link_to t(".action.edit"), edit_job_posting_path(@job_posting), class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= t(".title") %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="wrapper">
      <div class="page-content">
        <main role="main" id="main-display">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<% if @location.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @location, local: true do |form| %>
  <div class="field_with_errors">
    <%= form.label(:name, for: :location_name) %>
    <%= form.text_field(:name, id: :location_name, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:street_address_1, for: :location_street_address_1) %>
    <%= form.text_field(:street_address_1, id: :location_street_address_1, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:street_address_2, for: :location_street_address_2) %>
    <%= form.text_field(:street_address_2, id: :location_street_address_2, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:city, for: :location_city) %>
    <%= form.text_field(:city, id: :location_city, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:state, for: :location_state) %>
    <%= form.text_field(:state, id: :location_state, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:zip_code, for: :location_zip_code) %>
    <%= form.text_field(:zip_code, id: :location_zip_code, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:region_id, for: :location_region) %>
    <%= form.select(:region_id, Region.all.map { |region| [region.name, region.id] }, { prompt: t(".region_prompt") }, { id: :location_region, class: "form-control" }) %>
  </div>

  <%= form.submit action_name, class: "btn btn-default action-btn" %>
<% end %>

app/views/locations/_location_heading.html.erb
<div class="heading">
  <h1><%= t(".title") %></h1>
</div>

app/views/locations/new.html.erb
<%= render "location_heading" %>

<%= render "form", action_name: t("locations.form.create") %>

app/views/locations/show.html.erb
<%= render "location_heading" %>

<div class="location">
  <dl class="dl-horizontal">
    <dt><%= t(".name") %></dt>
    <dd class="location-name"><%= @location.name %></dd>
    <dt><%= t(".street_address_1") %></dt>
    <dd class="location-street-address-1"><%= @location.street_address_1 %></dd>
    <dt><%= t(".street_address_2") %></dt>
    <dd class="location-street-address-2"><%= @location.street_address_2 %></dd>
    <dt><%= t(".city") %></dt>
    <dd class="location-city"><%= @location.city %></dd>
    <dt><%= t(".state") %></dt>
    <dd class="location-state"><%= @location.state %></dd>
    <dt><%= t(".zip_code") %></dt>
    <dd class="location-zip-code"><%= @location.zip_code %></dd>
    <dt><%= t(".region") %></dt>
    <dd class="location-region"><%= @location.region.name %></dd>
  </dl>
</div>